name: CI/CD Pipeline for Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: pre-job # Dependencia del job anterior
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --prod

  test:
    runs-on: ubuntu-latest
    needs: build # Depende de que el job de build haya terminado
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watch=false --bail

  deploy:
    runs-on: ubuntu-latest
    needs: test # Depende de que el job de test haya pasado
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
